package com.approachingpi.timetime;
// Generated Oct 1, 2009 7:54:07 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "Company")
public class Company implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date dateCreated;
	private Date dateModified;
	private Set<Task> tasks = new HashSet<Task>(0);
	private Set<UserAccount> accounts = new HashSet<UserAccount>(0);

	public Company() {
	}

	public Company(String name, Date dateCreated, Date dateModified) {
		this.name = name;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}
	public Company(String name, Date dateCreated, Date dateModified,
			Set<Task> tasks, Set<UserAccount> accounts) {
		this.name = name;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.tasks = tasks;
		this.accounts = accounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCreated", nullable = false, length = 19)
	@NotNull
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateModified", nullable = false, length = 19)
	@NotNull
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<UserAccount> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<UserAccount> accounts) {
		this.accounts = accounts;
	}

}
