package com.approachingpi.timetime;
// Generated Oct 1, 2009 7:54:07 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TaskSummary generated by hbm2java
 */
@Entity
@Table(name = "TaskSummary")
public class TaskSummary implements java.io.Serializable {

	private Integer id;
	private Task task;
	private UserAccount account;
	private Date date;
	private Date dateCreated;
	private Date dateModified;
	private String notes;

	public TaskSummary() {
	}

	public TaskSummary(Task task, UserAccount account, Date date, Date dateCreated,
			Date dateModified) {
		this.task = task;
		this.account = account;
		this.date = date;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}
	public TaskSummary(Task task, UserAccount account, Date date, Date dateCreated,
			Date dateModified, String notes) {
		this.task = task;
		this.account = account;
		this.date = date;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.notes = notes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taskId", nullable = false)
	@NotNull
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountId", nullable = false)
	@NotNull
	public UserAccount getAccount() {
		return this.account;
	}

	public void setAccount(UserAccount account) {
		this.account = account;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	@NotNull
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCreated", nullable = false, length = 19)
	@NotNull
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateModified", nullable = false, length = 19)
	@NotNull
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "notes", length = 65535)
	@Length(max = 65535)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
