package com.approachingpi.timetime;
// Generated Oct 1, 2009 7:54:07 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * TimeSegment generated by hbm2java
 */
@Entity
@Table(name = "TimeSegment")
public class TimeSegment implements java.io.Serializable {

	private Integer id;
	private Task task;
	private UserAccount account;
	private Date dateStart;
	private Date dateReported;
	private Date dateEnd;

	public TimeSegment() {
	}

	public TimeSegment(Task task, UserAccount account) {
		this.task = task;
		this.account = account;
	}
	public TimeSegment(Task task, UserAccount account, Date dateStart,
			Date dateReported, Date dateEnd) {
		this.task = task;
		this.account = account;
		this.dateStart = dateStart;
		this.dateReported = dateReported;
		this.dateEnd = dateEnd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taskId", nullable = false)
	@NotNull
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountId", nullable = false)
	@NotNull
	public UserAccount getAccount() {
		return this.account;
	}

	public void setAccount(UserAccount account) {
		this.account = account;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateStart", length = 19)
	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateReported", length = 19)
	public Date getDateReported() {
		return this.dateReported;
	}

	public void setDateReported(Date dateReported) {
		this.dateReported = dateReported;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateEnd", length = 19)
	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

}
